kind: Job
apiVersion: batch/v1
metadata:
  name: myjob
spec:
  template:
    spec:
      containers:
      - name: contojob
        image: docker/whalesay
        command: ["cowsay","Hello This is Job Resource By Aslam Baba"]
      restartPolicy: Never
  backoffLimit: 3
  activeDeadlineSeconds: 60
