kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: myrs-with-yamlfile
spec:
  replicas: 10
  selector:
    matchLabels:
      admin: aslam
  template:
    metadata:
      name: conto
      labels:
        admin: aslam
    spec:
      containers:
      - name: sunny
        image: aamirpinger/helloworld
        ports:
        - containerPort: 80
