kind: Pod
apiVersion: v1
metadata:
  name: myreadinessprobe
spec:
  containers:
  - name: siramirhello
    image: aamirpinger/helloworld
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        port: 80
        path: /
